// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Square3_duplex.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Square3_duplex::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Square3_duplex::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<87> Square3_duplex::ap_ST_st1_fsm_0 = "1";
const sc_lv<87> Square3_duplex::ap_ST_st2_fsm_1 = "10";
const sc_lv<87> Square3_duplex::ap_ST_st3_fsm_2 = "100";
const sc_lv<87> Square3_duplex::ap_ST_st4_fsm_3 = "1000";
const sc_lv<87> Square3_duplex::ap_ST_st5_fsm_4 = "10000";
const sc_lv<87> Square3_duplex::ap_ST_st6_fsm_5 = "100000";
const sc_lv<87> Square3_duplex::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<87> Square3_duplex::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<87> Square3_duplex::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<87> Square3_duplex::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<87> Square3_duplex::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<87> Square3_duplex::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<87> Square3_duplex::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st25_fsm_24 = "1000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st26_fsm_25 = "10000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st27_fsm_26 = "100000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st28_fsm_27 = "1000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st29_fsm_28 = "10000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st30_fsm_29 = "100000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st31_fsm_30 = "1000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st32_fsm_31 = "10000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st33_fsm_32 = "100000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st34_fsm_33 = "1000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st35_fsm_34 = "10000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st36_fsm_35 = "100000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st37_fsm_36 = "1000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st38_fsm_37 = "10000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st39_fsm_38 = "100000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st40_fsm_39 = "1000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st41_fsm_40 = "10000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st42_fsm_41 = "100000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st43_fsm_42 = "1000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st44_fsm_43 = "10000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st45_fsm_44 = "100000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st46_fsm_45 = "1000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st47_fsm_46 = "10000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st48_fsm_47 = "100000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st49_fsm_48 = "1000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st50_fsm_49 = "10000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st51_fsm_50 = "100000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st52_fsm_51 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st53_fsm_52 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st54_fsm_53 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st55_fsm_54 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st56_fsm_55 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st57_fsm_56 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st58_fsm_57 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st59_fsm_58 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st60_fsm_59 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st61_fsm_60 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st62_fsm_61 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st63_fsm_62 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st64_fsm_63 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st65_fsm_64 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st66_fsm_65 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st67_fsm_66 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st68_fsm_67 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st69_fsm_68 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st70_fsm_69 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st71_fsm_70 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st72_fsm_71 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st73_fsm_72 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st74_fsm_73 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st75_fsm_74 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st76_fsm_75 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st77_fsm_76 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st78_fsm_77 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st79_fsm_78 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st80_fsm_79 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st81_fsm_80 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st82_fsm_81 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st83_fsm_82 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st84_fsm_83 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st85_fsm_84 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st86_fsm_85 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<87> Square3_duplex::ap_ST_st87_fsm_86 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> Square3_duplex::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Square3_duplex::ap_const_lv1_1 = "1";
const sc_lv<32> Square3_duplex::ap_const_lv32_47 = "1000111";
const sc_lv<32> Square3_duplex::ap_const_lv32_4F = "1001111";
const sc_lv<32> Square3_duplex::ap_const_lv32_1 = "1";
const sc_lv<1> Square3_duplex::ap_const_lv1_0 = "0";
const sc_lv<32> Square3_duplex::ap_const_lv32_12 = "10010";
const sc_lv<32> Square3_duplex::ap_const_lv32_13 = "10011";
const sc_lv<32> Square3_duplex::ap_const_lv32_14 = "10100";
const sc_lv<32> Square3_duplex::ap_const_lv32_44 = "1000100";
const sc_lv<32> Square3_duplex::ap_const_lv32_46 = "1000110";
const sc_lv<32> Square3_duplex::ap_const_lv32_4D = "1001101";
const sc_lv<32> Square3_duplex::ap_const_lv32_4E = "1001110";
const sc_lv<32> Square3_duplex::ap_const_lv32_55 = "1010101";
const sc_lv<32> Square3_duplex::ap_const_lv32_45 = "1000101";
const sc_lv<31> Square3_duplex::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<64> Square3_duplex::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> Square3_duplex::ap_const_lv64_A = "1010";
const sc_lv<129> Square3_duplex::ap_const_lv129_lc_1 = "11001100110011001100110011001100110011001100110011001100110011010";
const sc_lv<32> Square3_duplex::ap_const_lv32_3F = "111111";
const sc_lv<32> Square3_duplex::ap_const_lv32_1F = "11111";
const sc_lv<32> Square3_duplex::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> Square3_duplex::ap_const_lv32_80 = "10000000";
const sc_lv<129> Square3_duplex::ap_const_lv129_lc_2 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<31> Square3_duplex::ap_const_lv31_1 = "1";
const sc_lv<32> Square3_duplex::ap_const_lv32_48 = "1001000";
const sc_lv<2> Square3_duplex::ap_const_lv2_0 = "00";
const sc_lv<2> Square3_duplex::ap_const_lv2_1 = "1";
const sc_lv<32> Square3_duplex::ap_const_lv32_50 = "1010000";
const sc_lv<32> Square3_duplex::ap_const_lv32_56 = "1010110";

Square3_duplex::Square3_duplex(sc_module_name name) : sc_module(name), mVcdFile(0) {
    arr_U = new Square3_duplex_arr("arr_U");
    arr_U->clk(ap_clk);
    arr_U->reset(ap_rst);
    arr_U->address0(arr_address0);
    arr_U->ce0(arr_ce0);
    arr_U->we0(arr_we0);
    arr_U->d0(arr_d0);
    arr_U->q0(arr_q0);
    arr_U->address1(arr_address1);
    arr_U->ce1(arr_ce1);
    arr_U->q1(arr_q1);
    Square3_srem_64ns_5ns_32_68_seq_U1 = new Square3_srem_64ns_5ns_32_68_seq<1,68,64,5,32>("Square3_srem_64ns_5ns_32_68_seq_U1");
    Square3_srem_64ns_5ns_32_68_seq_U1->clk(ap_clk);
    Square3_srem_64ns_5ns_32_68_seq_U1->reset(ap_rst);
    Square3_srem_64ns_5ns_32_68_seq_U1->start(grp_fu_154_ap_start);
    Square3_srem_64ns_5ns_32_68_seq_U1->done(grp_fu_154_ap_done);
    Square3_srem_64ns_5ns_32_68_seq_U1->din0(y_reg_105);
    Square3_srem_64ns_5ns_32_68_seq_U1->din1(grp_fu_154_p1);
    Square3_srem_64ns_5ns_32_68_seq_U1->ce(ap_var_for_const0);
    Square3_srem_64ns_5ns_32_68_seq_U1->dout(grp_fu_154_p2);
    Square3_mul_66ns_64s_129_18_U2 = new Square3_mul_66ns_64s_129_18<1,18,66,64,129>("Square3_mul_66ns_64s_129_18_U2");
    Square3_mul_66ns_64s_129_18_U2->clk(ap_clk);
    Square3_mul_66ns_64s_129_18_U2->reset(ap_rst);
    Square3_mul_66ns_64s_129_18_U2->din0(grp_fu_164_p0);
    Square3_mul_66ns_64s_129_18_U2->din1(y_reg_105);
    Square3_mul_66ns_64s_129_18_U2->ce(ap_var_for_const0);
    Square3_mul_66ns_64s_129_18_U2->dout(grp_fu_164_p2);
    Square3_mul_32s_32s_32_6_U3 = new Square3_mul_32s_32s_32_6<1,6,32,32,32>("Square3_mul_32s_32s_32_6_U3");
    Square3_mul_32s_32s_32_6_U3->clk(ap_clk);
    Square3_mul_32s_32s_32_6_U3->reset(ap_rst);
    Square3_mul_32s_32s_32_6_U3->din0(reg_138);
    Square3_mul_32s_32s_32_6_U3->din1(arr_load_1_reg_511);
    Square3_mul_32s_32s_32_6_U3->ce(ap_var_for_const0);
    Square3_mul_32s_32s_32_6_U3->dout(grp_fu_336_p2);
    Square3_mul_32s_32s_32_6_U4 = new Square3_mul_32s_32s_32_6<1,6,32,32,32>("Square3_mul_32s_32s_32_6_U4");
    Square3_mul_32s_32s_32_6_U4->clk(ap_clk);
    Square3_mul_32s_32s_32_6_U4->reset(ap_rst);
    Square3_mul_32s_32s_32_6_U4->din0(reg_138);
    Square3_mul_32s_32s_32_6_U4->din1(reg_138);
    Square3_mul_32s_32s_32_6_U4->ce(ap_var_for_const0);
    Square3_mul_32s_32s_32_6_U4->dout(grp_fu_390_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st87_fsm_86 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st87_fsm_86 );

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_14_reg_526 );
    sensitive << ( z_reg_126 );
    sensitive << ( ap_sig_cseq_ST_st87_fsm_86 );
    sensitive << ( z_3_fu_396_p2 );

    SC_METHOD(thread_ap_sig_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_118);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_125);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_140);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_167);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_178);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_192);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_201);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_210);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_238);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_247);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_258);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_281);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_387);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_420);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_429);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_167 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_178 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_192 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_140 );

    SC_METHOD(thread_ap_sig_cseq_ST_st69_fsm_68);
    sensitive << ( ap_sig_201 );

    SC_METHOD(thread_ap_sig_cseq_ST_st70_fsm_69);
    sensitive << ( ap_sig_281 );

    SC_METHOD(thread_ap_sig_cseq_ST_st71_fsm_70);
    sensitive << ( ap_sig_210 );

    SC_METHOD(thread_ap_sig_cseq_ST_st72_fsm_71);
    sensitive << ( ap_sig_118 );

    SC_METHOD(thread_ap_sig_cseq_ST_st73_fsm_72);
    sensitive << ( ap_sig_387 );

    SC_METHOD(thread_ap_sig_cseq_ST_st78_fsm_77);
    sensitive << ( ap_sig_238 );

    SC_METHOD(thread_ap_sig_cseq_ST_st79_fsm_78);
    sensitive << ( ap_sig_247 );

    SC_METHOD(thread_ap_sig_cseq_ST_st80_fsm_79);
    sensitive << ( ap_sig_125 );

    SC_METHOD(thread_ap_sig_cseq_ST_st81_fsm_80);
    sensitive << ( ap_sig_420 );

    SC_METHOD(thread_ap_sig_cseq_ST_st86_fsm_85);
    sensitive << ( ap_sig_258 );

    SC_METHOD(thread_ap_sig_cseq_ST_st87_fsm_86);
    sensitive << ( ap_sig_429 );

    SC_METHOD(thread_arr_address0);
    sensitive << ( ap_sig_cseq_ST_st71_fsm_70 );
    sensitive << ( tmp_5_fu_303_p2 );
    sensitive << ( ap_sig_cseq_ST_st70_fsm_69 );
    sensitive << ( tmp_4_fu_294_p1 );
    sensitive << ( tmp_8_fu_319_p1 );
    sensitive << ( tmp_15_fu_332_p1 );

    SC_METHOD(thread_arr_address1);
    sensitive << ( ap_sig_cseq_ST_st71_fsm_70 );
    sensitive << ( tmp_9_fu_324_p1 );

    SC_METHOD(thread_arr_ce0);
    sensitive << ( ap_sig_cseq_ST_st71_fsm_70 );
    sensitive << ( tmp_5_fu_303_p2 );
    sensitive << ( ap_sig_cseq_ST_st70_fsm_69 );

    SC_METHOD(thread_arr_ce1);
    sensitive << ( ap_sig_cseq_ST_st71_fsm_70 );

    SC_METHOD(thread_arr_d0);
    sensitive << ( tmp_2_reg_478 );
    sensitive << ( ap_sig_cseq_ST_st70_fsm_69 );

    SC_METHOD(thread_arr_we0);
    sensitive << ( ap_sig_cseq_ST_st70_fsm_69 );

    SC_METHOD(thread_cou1_1_fu_148_p2);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_grp_fu_154_ap_start);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_142_p2 );

    SC_METHOD(thread_grp_fu_154_p1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_fu_164_p0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_i_1_fu_308_p2);
    sensitive << ( i_reg_115 );

    SC_METHOD(thread_i_cast_fu_299_p1);
    sensitive << ( i_reg_115 );

    SC_METHOD(thread_neg_mul_fu_250_p2);
    sensitive << ( mul_reg_453 );

    SC_METHOD(thread_neg_ti_fu_279_p2);
    sensitive << ( tmp_18_fu_272_p3 );

    SC_METHOD(thread_p_lshr_f_fu_212_p4);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_p_lshr_fu_192_p4);
    sensitive << ( p_neg_fu_186_p2 );

    SC_METHOD(thread_p_neg_fu_186_p2);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_p_neg_t_fu_206_p2);
    sensitive << ( tmp_10_fu_202_p1 );

    SC_METHOD(thread_tmp_10_fu_202_p1);
    sensitive << ( p_lshr_fu_192_p4 );

    SC_METHOD(thread_tmp_11_fu_222_p1);
    sensitive << ( p_lshr_f_fu_212_p4 );

    SC_METHOD(thread_tmp_13_fu_265_p1);
    sensitive << ( tmp_20_fu_255_p4 );

    SC_METHOD(thread_tmp_14_fu_384_p2);
    sensitive << ( ap_sig_cseq_ST_st80_fsm_79 );
    sensitive << ( tmp_24_fu_377_p3 );

    SC_METHOD(thread_tmp_15_fu_332_p1);
    sensitive << ( tmp_s_reg_442 );

    SC_METHOD(thread_tmp_17_fu_269_p1);
    sensitive << ( tmp_21_reg_458 );

    SC_METHOD(thread_tmp_18_fu_272_p3);
    sensitive << ( tmp_19_reg_426 );
    sensitive << ( tmp_17_fu_269_p1 );
    sensitive << ( tmp_13_fu_265_p1 );

    SC_METHOD(thread_tmp_20_fu_255_p4);
    sensitive << ( neg_mul_fu_250_p2 );

    SC_METHOD(thread_tmp_22_fu_341_p2);
    sensitive << ( tmp_1_reg_516 );

    SC_METHOD(thread_tmp_23_fu_369_p3);
    sensitive << ( tmp_25_fu_352_p1 );

    SC_METHOD(thread_tmp_24_fu_377_p3);
    sensitive << ( tmp_3_reg_432 );
    sensitive << ( tmp_28_fu_363_p2 );
    sensitive << ( tmp_23_fu_369_p3 );

    SC_METHOD(thread_tmp_25_fu_352_p1);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_tmp_26_fu_329_p1);
    sensitive << ( p_neg_reg_437 );

    SC_METHOD(thread_tmp_27_fu_356_p3);
    sensitive << ( tmp_26_reg_501 );

    SC_METHOD(thread_tmp_28_fu_363_p2);
    sensitive << ( tmp_27_fu_356_p3 );

    SC_METHOD(thread_tmp_3_fu_178_p3);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_tmp_4_fu_294_p1);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_tmp_5_fu_303_p2);
    sensitive << ( tmp_s_reg_442 );
    sensitive << ( ap_sig_cseq_ST_st71_fsm_70 );
    sensitive << ( i_cast_fu_299_p1 );

    SC_METHOD(thread_tmp_6_fu_234_p2);
    sensitive << ( cou1_reg_93 );

    SC_METHOD(thread_tmp_7_fu_314_p2);
    sensitive << ( tmp_6_reg_448 );
    sensitive << ( i_cast_fu_299_p1 );

    SC_METHOD(thread_tmp_8_fu_319_p1);
    sensitive << ( tmp_7_fu_314_p2 );

    SC_METHOD(thread_tmp_9_fu_324_p1);
    sensitive << ( i_reg_115 );

    SC_METHOD(thread_tmp_fu_142_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( y_reg_105 );

    SC_METHOD(thread_tmp_s_fu_226_p3);
    sensitive << ( tmp_3_fu_178_p3 );
    sensitive << ( p_neg_t_fu_206_p2 );
    sensitive << ( tmp_11_fu_222_p1 );

    SC_METHOD(thread_y_1_fu_285_p3);
    sensitive << ( tmp_19_reg_426 );
    sensitive << ( tmp_17_reg_463 );
    sensitive << ( neg_ti_reg_468 );

    SC_METHOD(thread_z_2_fu_346_p2);
    sensitive << ( z_reg_126 );
    sensitive << ( tmp_22_fu_341_p2 );

    SC_METHOD(thread_z_3_fu_396_p2);
    sensitive << ( tmp_16_reg_531 );
    sensitive << ( z_reg_126 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_142_p2 );
    sensitive << ( tmp_5_fu_303_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Square3_duplex_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_104, "ap_sig_104");
    sc_trace(mVcdFile, arr_q0, "arr_q0");
    sc_trace(mVcdFile, reg_138, "reg_138");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st72_fsm_71, "ap_sig_cseq_ST_st72_fsm_71");
    sc_trace(mVcdFile, ap_sig_118, "ap_sig_118");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st80_fsm_79, "ap_sig_cseq_ST_st80_fsm_79");
    sc_trace(mVcdFile, ap_sig_125, "ap_sig_125");
    sc_trace(mVcdFile, cou1_1_fu_148_p2, "cou1_1_fu_148_p2");
    sc_trace(mVcdFile, cou1_1_reg_416, "cou1_1_reg_416");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_140, "ap_sig_140");
    sc_trace(mVcdFile, tmp_fu_142_p2, "tmp_fu_142_p2");
    sc_trace(mVcdFile, tmp_19_reg_426, "tmp_19_reg_426");
    sc_trace(mVcdFile, tmp_3_fu_178_p3, "tmp_3_fu_178_p3");
    sc_trace(mVcdFile, tmp_3_reg_432, "tmp_3_reg_432");
    sc_trace(mVcdFile, p_neg_fu_186_p2, "p_neg_fu_186_p2");
    sc_trace(mVcdFile, p_neg_reg_437, "p_neg_reg_437");
    sc_trace(mVcdFile, tmp_s_fu_226_p3, "tmp_s_fu_226_p3");
    sc_trace(mVcdFile, tmp_s_reg_442, "tmp_s_reg_442");
    sc_trace(mVcdFile, tmp_6_fu_234_p2, "tmp_6_fu_234_p2");
    sc_trace(mVcdFile, tmp_6_reg_448, "tmp_6_reg_448");
    sc_trace(mVcdFile, grp_fu_164_p2, "grp_fu_164_p2");
    sc_trace(mVcdFile, mul_reg_453, "mul_reg_453");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_167, "ap_sig_167");
    sc_trace(mVcdFile, tmp_21_reg_458, "tmp_21_reg_458");
    sc_trace(mVcdFile, tmp_17_fu_269_p1, "tmp_17_fu_269_p1");
    sc_trace(mVcdFile, tmp_17_reg_463, "tmp_17_reg_463");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_178, "ap_sig_178");
    sc_trace(mVcdFile, neg_ti_fu_279_p2, "neg_ti_fu_279_p2");
    sc_trace(mVcdFile, neg_ti_reg_468, "neg_ti_reg_468");
    sc_trace(mVcdFile, y_1_fu_285_p3, "y_1_fu_285_p3");
    sc_trace(mVcdFile, y_1_reg_473, "y_1_reg_473");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_192, "ap_sig_192");
    sc_trace(mVcdFile, grp_fu_154_p2, "grp_fu_154_p2");
    sc_trace(mVcdFile, tmp_2_reg_478, "tmp_2_reg_478");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st69_fsm_68, "ap_sig_cseq_ST_st69_fsm_68");
    sc_trace(mVcdFile, ap_sig_201, "ap_sig_201");
    sc_trace(mVcdFile, i_1_fu_308_p2, "i_1_fu_308_p2");
    sc_trace(mVcdFile, i_1_reg_486, "i_1_reg_486");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st71_fsm_70, "ap_sig_cseq_ST_st71_fsm_70");
    sc_trace(mVcdFile, ap_sig_210, "ap_sig_210");
    sc_trace(mVcdFile, tmp_5_fu_303_p2, "tmp_5_fu_303_p2");
    sc_trace(mVcdFile, tmp_26_fu_329_p1, "tmp_26_fu_329_p1");
    sc_trace(mVcdFile, tmp_26_reg_501, "tmp_26_reg_501");
    sc_trace(mVcdFile, arr_q1, "arr_q1");
    sc_trace(mVcdFile, arr_load_1_reg_511, "arr_load_1_reg_511");
    sc_trace(mVcdFile, grp_fu_336_p2, "grp_fu_336_p2");
    sc_trace(mVcdFile, tmp_1_reg_516, "tmp_1_reg_516");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st78_fsm_77, "ap_sig_cseq_ST_st78_fsm_77");
    sc_trace(mVcdFile, ap_sig_238, "ap_sig_238");
    sc_trace(mVcdFile, z_2_fu_346_p2, "z_2_fu_346_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st79_fsm_78, "ap_sig_cseq_ST_st79_fsm_78");
    sc_trace(mVcdFile, ap_sig_247, "ap_sig_247");
    sc_trace(mVcdFile, tmp_14_fu_384_p2, "tmp_14_fu_384_p2");
    sc_trace(mVcdFile, tmp_14_reg_526, "tmp_14_reg_526");
    sc_trace(mVcdFile, grp_fu_390_p2, "grp_fu_390_p2");
    sc_trace(mVcdFile, tmp_16_reg_531, "tmp_16_reg_531");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st86_fsm_85, "ap_sig_cseq_ST_st86_fsm_85");
    sc_trace(mVcdFile, ap_sig_258, "ap_sig_258");
    sc_trace(mVcdFile, arr_address0, "arr_address0");
    sc_trace(mVcdFile, arr_ce0, "arr_ce0");
    sc_trace(mVcdFile, arr_we0, "arr_we0");
    sc_trace(mVcdFile, arr_d0, "arr_d0");
    sc_trace(mVcdFile, arr_address1, "arr_address1");
    sc_trace(mVcdFile, arr_ce1, "arr_ce1");
    sc_trace(mVcdFile, cou1_reg_93, "cou1_reg_93");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st70_fsm_69, "ap_sig_cseq_ST_st70_fsm_69");
    sc_trace(mVcdFile, ap_sig_281, "ap_sig_281");
    sc_trace(mVcdFile, y_reg_105, "y_reg_105");
    sc_trace(mVcdFile, i_reg_115, "i_reg_115");
    sc_trace(mVcdFile, z_reg_126, "z_reg_126");
    sc_trace(mVcdFile, tmp_4_fu_294_p1, "tmp_4_fu_294_p1");
    sc_trace(mVcdFile, tmp_8_fu_319_p1, "tmp_8_fu_319_p1");
    sc_trace(mVcdFile, tmp_9_fu_324_p1, "tmp_9_fu_324_p1");
    sc_trace(mVcdFile, tmp_15_fu_332_p1, "tmp_15_fu_332_p1");
    sc_trace(mVcdFile, grp_fu_154_p1, "grp_fu_154_p1");
    sc_trace(mVcdFile, grp_fu_164_p0, "grp_fu_164_p0");
    sc_trace(mVcdFile, p_lshr_fu_192_p4, "p_lshr_fu_192_p4");
    sc_trace(mVcdFile, tmp_10_fu_202_p1, "tmp_10_fu_202_p1");
    sc_trace(mVcdFile, p_lshr_f_fu_212_p4, "p_lshr_f_fu_212_p4");
    sc_trace(mVcdFile, p_neg_t_fu_206_p2, "p_neg_t_fu_206_p2");
    sc_trace(mVcdFile, tmp_11_fu_222_p1, "tmp_11_fu_222_p1");
    sc_trace(mVcdFile, neg_mul_fu_250_p2, "neg_mul_fu_250_p2");
    sc_trace(mVcdFile, tmp_20_fu_255_p4, "tmp_20_fu_255_p4");
    sc_trace(mVcdFile, tmp_13_fu_265_p1, "tmp_13_fu_265_p1");
    sc_trace(mVcdFile, tmp_18_fu_272_p3, "tmp_18_fu_272_p3");
    sc_trace(mVcdFile, i_cast_fu_299_p1, "i_cast_fu_299_p1");
    sc_trace(mVcdFile, tmp_7_fu_314_p2, "tmp_7_fu_314_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st73_fsm_72, "ap_sig_cseq_ST_st73_fsm_72");
    sc_trace(mVcdFile, ap_sig_387, "ap_sig_387");
    sc_trace(mVcdFile, tmp_22_fu_341_p2, "tmp_22_fu_341_p2");
    sc_trace(mVcdFile, tmp_27_fu_356_p3, "tmp_27_fu_356_p3");
    sc_trace(mVcdFile, tmp_25_fu_352_p1, "tmp_25_fu_352_p1");
    sc_trace(mVcdFile, tmp_28_fu_363_p2, "tmp_28_fu_363_p2");
    sc_trace(mVcdFile, tmp_23_fu_369_p3, "tmp_23_fu_369_p3");
    sc_trace(mVcdFile, tmp_24_fu_377_p3, "tmp_24_fu_377_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st81_fsm_80, "ap_sig_cseq_ST_st81_fsm_80");
    sc_trace(mVcdFile, ap_sig_420, "ap_sig_420");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st87_fsm_86, "ap_sig_cseq_ST_st87_fsm_86");
    sc_trace(mVcdFile, ap_sig_429, "ap_sig_429");
    sc_trace(mVcdFile, z_3_fu_396_p2, "z_3_fu_396_p2");
    sc_trace(mVcdFile, grp_fu_154_ap_start, "grp_fu_154_ap_start");
    sc_trace(mVcdFile, grp_fu_154_ap_done, "grp_fu_154_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Square3_duplex::~Square3_duplex() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete arr_U;
    delete Square3_srem_64ns_5ns_32_68_seq_U1;
    delete Square3_mul_66ns_64s_129_18_U2;
    delete Square3_mul_32s_32s_32_6_U3;
    delete Square3_mul_32s_32s_32_6_U4;
}

void Square3_duplex::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Square3_duplex::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st70_fsm_69.read())) {
        cou1_reg_93 = cou1_1_reg_416.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        cou1_reg_93 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_142_p2.read(), ap_const_lv1_0))) {
        i_reg_115 = ap_const_lv31_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st79_fsm_78.read())) {
        i_reg_115 = i_1_reg_486.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st70_fsm_69.read())) {
        y_reg_105 = y_1_reg_473.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        y_reg_105 = x.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_142_p2.read(), ap_const_lv1_0))) {
        z_reg_126 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st79_fsm_78.read())) {
        z_reg_126 = z_2_fu_346_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st72_fsm_71.read())) {
        arr_load_1_reg_511 = arr_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        cou1_1_reg_416 = cou1_1_fu_148_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read())) {
        i_1_reg_486 = i_1_fu_308_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        mul_reg_453 = grp_fu_164_p2.read();
        tmp_21_reg_458 = grp_fu_164_p2.read().range(128, 68);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_reg_426.read()))) {
        neg_ti_reg_468 = neg_ti_fu_279_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(tmp_fu_142_p2.read(), ap_const_lv1_0))) {
        p_neg_reg_437 = p_neg_fu_186_p2.read();
        tmp_3_reg_432 = cou1_reg_93.read().range(31, 31);
        tmp_6_reg_448 = tmp_6_fu_234_p2.read();
        tmp_s_reg_442 = tmp_s_fu_226_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st72_fsm_71.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st80_fsm_79.read()))) {
        reg_138 = arr_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st80_fsm_79.read())) {
        tmp_14_reg_526 = tmp_14_fu_384_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st86_fsm_85.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_14_reg_526.read()))) {
        tmp_16_reg_531 = grp_fu_390_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        tmp_17_reg_463 = tmp_17_fu_269_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(tmp_fu_142_p2.read(), ap_const_lv1_0))) {
        tmp_19_reg_426 = y_reg_105.read().range(63, 63);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st78_fsm_77.read())) {
        tmp_1_reg_516 = grp_fu_336_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_303_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_432.read()))) {
        tmp_26_reg_501 = tmp_26_fu_329_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st69_fsm_68.read())) {
        tmp_2_reg_478 = grp_fu_154_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        y_1_reg_473 = y_1_fu_285_p3.read();
    }
}

void Square3_duplex::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st87_fsm_86.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st87_fsm_86.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_return() {
    ap_return = (!tmp_14_reg_526.read()[0].is_01())? sc_lv<32>(): ((tmp_14_reg_526.read()[0].to_bool())? z_3_fu_396_p2.read(): z_reg_126.read());
}

void Square3_duplex::thread_ap_sig_104() {
    ap_sig_104 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void Square3_duplex::thread_ap_sig_118() {
    ap_sig_118 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(71, 71));
}

void Square3_duplex::thread_ap_sig_125() {
    ap_sig_125 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(79, 79));
}

void Square3_duplex::thread_ap_sig_140() {
    ap_sig_140 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void Square3_duplex::thread_ap_sig_167() {
    ap_sig_167 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void Square3_duplex::thread_ap_sig_178() {
    ap_sig_178 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void Square3_duplex::thread_ap_sig_192() {
    ap_sig_192 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void Square3_duplex::thread_ap_sig_201() {
    ap_sig_201 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(68, 68));
}

void Square3_duplex::thread_ap_sig_210() {
    ap_sig_210 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(70, 70));
}

void Square3_duplex::thread_ap_sig_238() {
    ap_sig_238 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(77, 77));
}

void Square3_duplex::thread_ap_sig_247() {
    ap_sig_247 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(78, 78));
}

void Square3_duplex::thread_ap_sig_258() {
    ap_sig_258 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(85, 85));
}

void Square3_duplex::thread_ap_sig_281() {
    ap_sig_281 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(69, 69));
}

void Square3_duplex::thread_ap_sig_387() {
    ap_sig_387 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(72, 72));
}

void Square3_duplex::thread_ap_sig_420() {
    ap_sig_420 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(80, 80));
}

void Square3_duplex::thread_ap_sig_429() {
    ap_sig_429 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(86, 86));
}

void Square3_duplex::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_167.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_104.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_178.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_192.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_140.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st69_fsm_68() {
    if (ap_sig_201.read()) {
        ap_sig_cseq_ST_st69_fsm_68 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st69_fsm_68 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st70_fsm_69() {
    if (ap_sig_281.read()) {
        ap_sig_cseq_ST_st70_fsm_69 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st70_fsm_69 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st71_fsm_70() {
    if (ap_sig_210.read()) {
        ap_sig_cseq_ST_st71_fsm_70 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st71_fsm_70 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st72_fsm_71() {
    if (ap_sig_118.read()) {
        ap_sig_cseq_ST_st72_fsm_71 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st72_fsm_71 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st73_fsm_72() {
    if (ap_sig_387.read()) {
        ap_sig_cseq_ST_st73_fsm_72 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st73_fsm_72 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st78_fsm_77() {
    if (ap_sig_238.read()) {
        ap_sig_cseq_ST_st78_fsm_77 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st78_fsm_77 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st79_fsm_78() {
    if (ap_sig_247.read()) {
        ap_sig_cseq_ST_st79_fsm_78 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st79_fsm_78 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st80_fsm_79() {
    if (ap_sig_125.read()) {
        ap_sig_cseq_ST_st80_fsm_79 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st80_fsm_79 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st81_fsm_80() {
    if (ap_sig_420.read()) {
        ap_sig_cseq_ST_st81_fsm_80 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st81_fsm_80 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st86_fsm_85() {
    if (ap_sig_258.read()) {
        ap_sig_cseq_ST_st86_fsm_85 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st86_fsm_85 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_ap_sig_cseq_ST_st87_fsm_86() {
    if (ap_sig_429.read()) {
        ap_sig_cseq_ST_st87_fsm_86 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st87_fsm_86 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_arr_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st70_fsm_69.read())) {
        arr_address0 =  (sc_lv<5>) (tmp_4_fu_294_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_303_p2.read()))) {
        arr_address0 =  (sc_lv<5>) (tmp_15_fu_332_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_303_p2.read()))) {
        arr_address0 =  (sc_lv<5>) (tmp_8_fu_319_p1.read());
    } else {
        arr_address0 = "XXXXX";
    }
}

void Square3_duplex::thread_arr_address1() {
    arr_address1 =  (sc_lv<5>) (tmp_9_fu_324_p1.read());
}

void Square3_duplex::thread_arr_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_303_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_303_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st70_fsm_69.read()))) {
        arr_ce0 = ap_const_logic_1;
    } else {
        arr_ce0 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_arr_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st71_fsm_70.read())) {
        arr_ce1 = ap_const_logic_1;
    } else {
        arr_ce1 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_arr_d0() {
    arr_d0 = tmp_2_reg_478.read().range(32-1, 0);
}

void Square3_duplex::thread_arr_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st70_fsm_69.read()))) {
        arr_we0 = ap_const_logic_1;
    } else {
        arr_we0 = ap_const_logic_0;
    }
}

void Square3_duplex::thread_cou1_1_fu_148_p2() {
    cou1_1_fu_148_p2 = (!cou1_reg_93.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(cou1_reg_93.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void Square3_duplex::thread_grp_fu_154_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_fu_142_p2.read(), ap_const_lv1_0))) {
        grp_fu_154_ap_start = ap_const_logic_1;
    } else {
        grp_fu_154_ap_start = ap_const_logic_0;
    }
}

void Square3_duplex::thread_grp_fu_154_p1() {
    grp_fu_154_p1 =  (sc_lv<5>) (ap_const_lv64_A);
}

void Square3_duplex::thread_grp_fu_164_p0() {
    grp_fu_164_p0 =  (sc_lv<66>) (ap_const_lv129_lc_1);
}

void Square3_duplex::thread_i_1_fu_308_p2() {
    i_1_fu_308_p2 = (!i_reg_115.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i_reg_115.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void Square3_duplex::thread_i_cast_fu_299_p1() {
    i_cast_fu_299_p1 = esl_zext<32,31>(i_reg_115.read());
}

void Square3_duplex::thread_neg_mul_fu_250_p2() {
    neg_mul_fu_250_p2 = (!ap_const_lv129_lc_2.is_01() || !mul_reg_453.read().is_01())? sc_lv<129>(): (sc_biguint<129>(ap_const_lv129_lc_2) - sc_biguint<129>(mul_reg_453.read()));
}

void Square3_duplex::thread_neg_ti_fu_279_p2() {
    neg_ti_fu_279_p2 = (!ap_const_lv64_0.is_01() || !tmp_18_fu_272_p3.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_0) - sc_biguint<64>(tmp_18_fu_272_p3.read()));
}

void Square3_duplex::thread_p_lshr_f_fu_212_p4() {
    p_lshr_f_fu_212_p4 = cou1_reg_93.read().range(31, 1);
}

void Square3_duplex::thread_p_lshr_fu_192_p4() {
    p_lshr_fu_192_p4 = p_neg_fu_186_p2.read().range(31, 1);
}

void Square3_duplex::thread_p_neg_fu_186_p2() {
    p_neg_fu_186_p2 = (!ap_const_lv32_0.is_01() || !cou1_reg_93.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(cou1_reg_93.read()));
}

void Square3_duplex::thread_p_neg_t_fu_206_p2() {
    p_neg_t_fu_206_p2 = (!ap_const_lv32_0.is_01() || !tmp_10_fu_202_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_10_fu_202_p1.read()));
}

void Square3_duplex::thread_tmp_10_fu_202_p1() {
    tmp_10_fu_202_p1 = esl_zext<32,31>(p_lshr_fu_192_p4.read());
}

void Square3_duplex::thread_tmp_11_fu_222_p1() {
    tmp_11_fu_222_p1 = esl_zext<32,31>(p_lshr_f_fu_212_p4.read());
}

void Square3_duplex::thread_tmp_13_fu_265_p1() {
    tmp_13_fu_265_p1 = esl_sext<64,61>(tmp_20_fu_255_p4.read());
}

void Square3_duplex::thread_tmp_14_fu_384_p2() {
    tmp_14_fu_384_p2 = (!tmp_24_fu_377_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_fu_377_p3.read() == ap_const_lv2_1);
}

void Square3_duplex::thread_tmp_15_fu_332_p1() {
    tmp_15_fu_332_p1 = esl_sext<64,32>(tmp_s_reg_442.read());
}

void Square3_duplex::thread_tmp_17_fu_269_p1() {
    tmp_17_fu_269_p1 = esl_sext<64,61>(tmp_21_reg_458.read());
}

void Square3_duplex::thread_tmp_18_fu_272_p3() {
    tmp_18_fu_272_p3 = (!tmp_19_reg_426.read()[0].is_01())? sc_lv<64>(): ((tmp_19_reg_426.read()[0].to_bool())? tmp_13_fu_265_p1.read(): tmp_17_fu_269_p1.read());
}

void Square3_duplex::thread_tmp_20_fu_255_p4() {
    tmp_20_fu_255_p4 = neg_mul_fu_250_p2.read().range(128, 68);
}

void Square3_duplex::thread_tmp_22_fu_341_p2() {
    tmp_22_fu_341_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): tmp_1_reg_516.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void Square3_duplex::thread_tmp_23_fu_369_p3() {
    tmp_23_fu_369_p3 = esl_concat<1,1>(ap_const_lv1_0, tmp_25_fu_352_p1.read());
}

void Square3_duplex::thread_tmp_24_fu_377_p3() {
    tmp_24_fu_377_p3 = (!tmp_3_reg_432.read()[0].is_01())? sc_lv<2>(): ((tmp_3_reg_432.read()[0].to_bool())? tmp_28_fu_363_p2.read(): tmp_23_fu_369_p3.read());
}

void Square3_duplex::thread_tmp_25_fu_352_p1() {
    tmp_25_fu_352_p1 = cou1_reg_93.read().range(1-1, 0);
}

void Square3_duplex::thread_tmp_26_fu_329_p1() {
    tmp_26_fu_329_p1 = p_neg_reg_437.read().range(1-1, 0);
}

void Square3_duplex::thread_tmp_27_fu_356_p3() {
    tmp_27_fu_356_p3 = esl_concat<1,1>(ap_const_lv1_0, tmp_26_reg_501.read());
}

void Square3_duplex::thread_tmp_28_fu_363_p2() {
    tmp_28_fu_363_p2 = (!ap_const_lv2_0.is_01() || !tmp_27_fu_356_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_0) - sc_biguint<2>(tmp_27_fu_356_p3.read()));
}

void Square3_duplex::thread_tmp_3_fu_178_p3() {
    tmp_3_fu_178_p3 = cou1_reg_93.read().range(31, 31);
}

void Square3_duplex::thread_tmp_4_fu_294_p1() {
    tmp_4_fu_294_p1 = esl_sext<64,32>(cou1_reg_93.read());
}

void Square3_duplex::thread_tmp_5_fu_303_p2() {
    tmp_5_fu_303_p2 = (!i_cast_fu_299_p1.read().is_01() || !tmp_s_reg_442.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_cast_fu_299_p1.read()) < sc_bigint<32>(tmp_s_reg_442.read()));
}

void Square3_duplex::thread_tmp_6_fu_234_p2() {
    tmp_6_fu_234_p2 = (!cou1_reg_93.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(cou1_reg_93.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void Square3_duplex::thread_tmp_7_fu_314_p2() {
    tmp_7_fu_314_p2 = (!tmp_6_reg_448.read().is_01() || !i_cast_fu_299_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_6_reg_448.read()) - sc_biguint<32>(i_cast_fu_299_p1.read()));
}

void Square3_duplex::thread_tmp_8_fu_319_p1() {
    tmp_8_fu_319_p1 = esl_sext<64,32>(tmp_7_fu_314_p2.read());
}

void Square3_duplex::thread_tmp_9_fu_324_p1() {
    tmp_9_fu_324_p1 = esl_zext<64,31>(i_reg_115.read());
}

void Square3_duplex::thread_tmp_fu_142_p2() {
    tmp_fu_142_p2 = (!y_reg_105.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(y_reg_105.read() == ap_const_lv64_0);
}

void Square3_duplex::thread_tmp_s_fu_226_p3() {
    tmp_s_fu_226_p3 = (!tmp_3_fu_178_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_178_p3.read()[0].to_bool())? p_neg_t_fu_206_p2.read(): tmp_11_fu_222_p1.read());
}

void Square3_duplex::thread_y_1_fu_285_p3() {
    y_1_fu_285_p3 = (!tmp_19_reg_426.read()[0].is_01())? sc_lv<64>(): ((tmp_19_reg_426.read()[0].to_bool())? neg_ti_reg_468.read(): tmp_17_reg_463.read());
}

void Square3_duplex::thread_z_2_fu_346_p2() {
    z_2_fu_346_p2 = (!z_reg_126.read().is_01() || !tmp_22_fu_341_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(z_reg_126.read()) + sc_biguint<32>(tmp_22_fu_341_p2.read()));
}

void Square3_duplex::thread_z_3_fu_396_p2() {
    z_3_fu_396_p2 = (!z_reg_126.read().is_01() || !tmp_16_reg_531.read().is_01())? sc_lv<32>(): (sc_biguint<32>(z_reg_126.read()) + sc_biguint<32>(tmp_16_reg_531.read()));
}

void Square3_duplex::thread_ap_NS_fsm() {
    if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st1_fsm_0))
    {
        if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
            ap_NS_fsm = ap_ST_st2_fsm_1;
        } else {
            ap_NS_fsm = ap_ST_st1_fsm_0;
        }
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st2_fsm_1))
    {
        if (!esl_seteq<1,1,1>(tmp_fu_142_p2.read(), ap_const_lv1_0)) {
            ap_NS_fsm = ap_ST_st71_fsm_70;
        } else {
            ap_NS_fsm = ap_ST_st3_fsm_2;
        }
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st3_fsm_2))
    {
        ap_NS_fsm = ap_ST_st4_fsm_3;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st4_fsm_3))
    {
        ap_NS_fsm = ap_ST_st5_fsm_4;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st5_fsm_4))
    {
        ap_NS_fsm = ap_ST_st6_fsm_5;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st6_fsm_5))
    {
        ap_NS_fsm = ap_ST_st7_fsm_6;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st7_fsm_6))
    {
        ap_NS_fsm = ap_ST_st8_fsm_7;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st8_fsm_7))
    {
        ap_NS_fsm = ap_ST_st9_fsm_8;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st9_fsm_8))
    {
        ap_NS_fsm = ap_ST_st10_fsm_9;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st10_fsm_9))
    {
        ap_NS_fsm = ap_ST_st11_fsm_10;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st11_fsm_10))
    {
        ap_NS_fsm = ap_ST_st12_fsm_11;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st12_fsm_11))
    {
        ap_NS_fsm = ap_ST_st13_fsm_12;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st13_fsm_12))
    {
        ap_NS_fsm = ap_ST_st14_fsm_13;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st14_fsm_13))
    {
        ap_NS_fsm = ap_ST_st15_fsm_14;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st15_fsm_14))
    {
        ap_NS_fsm = ap_ST_st16_fsm_15;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st16_fsm_15))
    {
        ap_NS_fsm = ap_ST_st17_fsm_16;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st17_fsm_16))
    {
        ap_NS_fsm = ap_ST_st18_fsm_17;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st18_fsm_17))
    {
        ap_NS_fsm = ap_ST_st19_fsm_18;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st19_fsm_18))
    {
        ap_NS_fsm = ap_ST_st20_fsm_19;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st20_fsm_19))
    {
        ap_NS_fsm = ap_ST_st21_fsm_20;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st21_fsm_20))
    {
        ap_NS_fsm = ap_ST_st22_fsm_21;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st22_fsm_21))
    {
        ap_NS_fsm = ap_ST_st23_fsm_22;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st23_fsm_22))
    {
        ap_NS_fsm = ap_ST_st24_fsm_23;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st24_fsm_23))
    {
        ap_NS_fsm = ap_ST_st25_fsm_24;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st25_fsm_24))
    {
        ap_NS_fsm = ap_ST_st26_fsm_25;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st26_fsm_25))
    {
        ap_NS_fsm = ap_ST_st27_fsm_26;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st27_fsm_26))
    {
        ap_NS_fsm = ap_ST_st28_fsm_27;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st28_fsm_27))
    {
        ap_NS_fsm = ap_ST_st29_fsm_28;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st29_fsm_28))
    {
        ap_NS_fsm = ap_ST_st30_fsm_29;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st30_fsm_29))
    {
        ap_NS_fsm = ap_ST_st31_fsm_30;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st31_fsm_30))
    {
        ap_NS_fsm = ap_ST_st32_fsm_31;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st32_fsm_31))
    {
        ap_NS_fsm = ap_ST_st33_fsm_32;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st33_fsm_32))
    {
        ap_NS_fsm = ap_ST_st34_fsm_33;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st34_fsm_33))
    {
        ap_NS_fsm = ap_ST_st35_fsm_34;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st35_fsm_34))
    {
        ap_NS_fsm = ap_ST_st36_fsm_35;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st36_fsm_35))
    {
        ap_NS_fsm = ap_ST_st37_fsm_36;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st37_fsm_36))
    {
        ap_NS_fsm = ap_ST_st38_fsm_37;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st38_fsm_37))
    {
        ap_NS_fsm = ap_ST_st39_fsm_38;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st39_fsm_38))
    {
        ap_NS_fsm = ap_ST_st40_fsm_39;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st40_fsm_39))
    {
        ap_NS_fsm = ap_ST_st41_fsm_40;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st41_fsm_40))
    {
        ap_NS_fsm = ap_ST_st42_fsm_41;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st42_fsm_41))
    {
        ap_NS_fsm = ap_ST_st43_fsm_42;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st43_fsm_42))
    {
        ap_NS_fsm = ap_ST_st44_fsm_43;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st44_fsm_43))
    {
        ap_NS_fsm = ap_ST_st45_fsm_44;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st45_fsm_44))
    {
        ap_NS_fsm = ap_ST_st46_fsm_45;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st46_fsm_45))
    {
        ap_NS_fsm = ap_ST_st47_fsm_46;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st47_fsm_46))
    {
        ap_NS_fsm = ap_ST_st48_fsm_47;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st48_fsm_47))
    {
        ap_NS_fsm = ap_ST_st49_fsm_48;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st49_fsm_48))
    {
        ap_NS_fsm = ap_ST_st50_fsm_49;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st50_fsm_49))
    {
        ap_NS_fsm = ap_ST_st51_fsm_50;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st51_fsm_50))
    {
        ap_NS_fsm = ap_ST_st52_fsm_51;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st52_fsm_51))
    {
        ap_NS_fsm = ap_ST_st53_fsm_52;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st53_fsm_52))
    {
        ap_NS_fsm = ap_ST_st54_fsm_53;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st54_fsm_53))
    {
        ap_NS_fsm = ap_ST_st55_fsm_54;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st55_fsm_54))
    {
        ap_NS_fsm = ap_ST_st56_fsm_55;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st56_fsm_55))
    {
        ap_NS_fsm = ap_ST_st57_fsm_56;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st57_fsm_56))
    {
        ap_NS_fsm = ap_ST_st58_fsm_57;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st58_fsm_57))
    {
        ap_NS_fsm = ap_ST_st59_fsm_58;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st59_fsm_58))
    {
        ap_NS_fsm = ap_ST_st60_fsm_59;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st60_fsm_59))
    {
        ap_NS_fsm = ap_ST_st61_fsm_60;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st61_fsm_60))
    {
        ap_NS_fsm = ap_ST_st62_fsm_61;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st62_fsm_61))
    {
        ap_NS_fsm = ap_ST_st63_fsm_62;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st63_fsm_62))
    {
        ap_NS_fsm = ap_ST_st64_fsm_63;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st64_fsm_63))
    {
        ap_NS_fsm = ap_ST_st65_fsm_64;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st65_fsm_64))
    {
        ap_NS_fsm = ap_ST_st66_fsm_65;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st66_fsm_65))
    {
        ap_NS_fsm = ap_ST_st67_fsm_66;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st67_fsm_66))
    {
        ap_NS_fsm = ap_ST_st68_fsm_67;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st68_fsm_67))
    {
        ap_NS_fsm = ap_ST_st69_fsm_68;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st69_fsm_68))
    {
        ap_NS_fsm = ap_ST_st70_fsm_69;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st70_fsm_69))
    {
        ap_NS_fsm = ap_ST_st2_fsm_1;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st71_fsm_70))
    {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_303_p2.read())) {
            ap_NS_fsm = ap_ST_st80_fsm_79;
        } else {
            ap_NS_fsm = ap_ST_st72_fsm_71;
        }
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st72_fsm_71))
    {
        ap_NS_fsm = ap_ST_st73_fsm_72;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st73_fsm_72))
    {
        ap_NS_fsm = ap_ST_st74_fsm_73;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st74_fsm_73))
    {
        ap_NS_fsm = ap_ST_st75_fsm_74;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st75_fsm_74))
    {
        ap_NS_fsm = ap_ST_st76_fsm_75;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st76_fsm_75))
    {
        ap_NS_fsm = ap_ST_st77_fsm_76;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st77_fsm_76))
    {
        ap_NS_fsm = ap_ST_st78_fsm_77;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st78_fsm_77))
    {
        ap_NS_fsm = ap_ST_st79_fsm_78;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st79_fsm_78))
    {
        ap_NS_fsm = ap_ST_st71_fsm_70;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st80_fsm_79))
    {
        ap_NS_fsm = ap_ST_st81_fsm_80;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st81_fsm_80))
    {
        ap_NS_fsm = ap_ST_st82_fsm_81;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st82_fsm_81))
    {
        ap_NS_fsm = ap_ST_st83_fsm_82;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st83_fsm_82))
    {
        ap_NS_fsm = ap_ST_st84_fsm_83;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st84_fsm_83))
    {
        ap_NS_fsm = ap_ST_st85_fsm_84;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st85_fsm_84))
    {
        ap_NS_fsm = ap_ST_st86_fsm_85;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st86_fsm_85))
    {
        ap_NS_fsm = ap_ST_st87_fsm_86;
    }
    else if (esl_seteq<1,87,87>(ap_CS_fsm.read(), ap_ST_st87_fsm_86))
    {
        ap_NS_fsm = ap_ST_st1_fsm_0;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<87>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

