// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Square_root_dup_HH_
#define _Square_root_dup_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Square_root_srem_51ns_5ns_5_55_seq.h"
#include "Square_root_mul_54ns_51s_105_5.h"
#include "Square_root_mac_muladd_5s_5s_15s_32_1.h"
#include "Square_root_dup_arr.h"

namespace ap_rtl {

struct Square_root_dup : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Square_root_dup(sc_module_name name);
    SC_HAS_PROCESS(Square_root_dup);

    ~Square_root_dup();

    sc_trace_file* mVcdFile;

    Square_root_dup_arr* arr_U;
    Square_root_srem_51ns_5ns_5_55_seq<1,55,51,5,5>* Square_root_srem_51ns_5ns_5_55_seq_U1;
    Square_root_mul_54ns_51s_105_5<1,5,54,51,105>* Square_root_mul_54ns_51s_105_5_U2;
    Square_root_mac_muladd_5s_5s_15s_32_1<1,1,5,5,15,32>* Square_root_mac_muladd_5s_5s_15s_32_1_U3;
    sc_signal< sc_lv<59> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_76;
    sc_signal< sc_lv<52> > x_assign_cast_cast_cast_fu_177_p1;
    sc_signal< sc_lv<64> > cou1_cast_fu_181_p1;
    sc_signal< sc_lv<64> > cou1_cast_reg_396;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_95;
    sc_signal< sc_lv<5> > cou1_fu_191_p2;
    sc_signal< sc_lv<5> > cou1_reg_404;
    sc_signal< sc_lv<1> > tmp_fu_185_p2;
    sc_signal< sc_lv<1> > tmp_16_reg_414;
    sc_signal< sc_lv<1> > tmp_3_fu_221_p1;
    sc_signal< sc_lv<1> > tmp_3_reg_420;
    sc_signal< sc_lv<4> > p_lshr_f_cast_fu_229_p4;
    sc_signal< sc_lv<4> > p_lshr_f_cast_reg_425;
    sc_signal< sc_lv<64> > tmp_1_cast_fu_239_p1;
    sc_signal< sc_lv<64> > tmp_1_cast_reg_430;
    sc_signal< sc_lv<6> > tmp_6_fu_243_p2;
    sc_signal< sc_lv<6> > tmp_6_reg_435;
    sc_signal< sc_lv<105> > grp_fu_207_p2;
    sc_signal< sc_lv<105> > mul_reg_440;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_124;
    sc_signal< sc_lv<49> > tmp_18_reg_445;
    sc_signal< sc_lv<52> > tmp_14_fu_294_p3;
    sc_signal< sc_lv<52> > tmp_14_reg_450;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_135;
    sc_signal< sc_lv<4> > i_1_fu_320_p2;
    sc_signal< sc_lv<4> > i_1_reg_458;
    sc_signal< sc_logic > ap_sig_cseq_ST_st57_fsm_56;
    sc_signal< bool > ap_sig_144;
    sc_signal< sc_lv<1> > exitcond_fu_315_p2;
    sc_signal< sc_lv<15> > z_1_fu_362_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st58_fsm_57;
    sc_signal< bool > ap_sig_167;
    sc_signal< sc_lv<5> > arr_address0;
    sc_signal< sc_logic > arr_ce0;
    sc_signal< sc_logic > arr_we0;
    sc_signal< sc_lv<5> > arr_d0;
    sc_signal< sc_lv<5> > arr_q0;
    sc_signal< sc_lv<5> > arr_address1;
    sc_signal< sc_logic > arr_ce1;
    sc_signal< sc_lv<5> > arr_q1;
    sc_signal< sc_lv<5> > indvars_iv_reg_103;
    sc_signal< sc_logic > ap_sig_cseq_ST_st56_fsm_55;
    sc_signal< bool > ap_sig_189;
    sc_signal< sc_lv<52> > y1_reg_114;
    sc_signal< sc_lv<4> > i_reg_124;
    sc_signal< sc_lv<15> > z_reg_135;
    sc_signal< sc_lv<64> > tmp_7_cast_fu_331_p1;
    sc_signal< sc_lv<64> > i_cast_fu_310_p1;
    sc_signal< sc_lv<35> > p_shl_fu_147_p3;
    sc_signal< sc_lv<33> > p_shl1_fu_159_p3;
    sc_signal< sc_lv<36> > p_shl_cast_fu_155_p1;
    sc_signal< sc_lv<36> > p_shl1_cast_fu_167_p1;
    sc_signal< sc_lv<36> > y_fu_171_p2;
    sc_signal< sc_lv<51> > grp_fu_197_p0;
    sc_signal< sc_lv<5> > grp_fu_197_p1;
    sc_signal< sc_lv<54> > grp_fu_207_p0;
    sc_signal< sc_lv<51> > grp_fu_207_p1;
    sc_signal< sc_lv<6> > cou1_cast2_fu_225_p1;
    sc_signal< sc_lv<105> > neg_mul_fu_259_p2;
    sc_signal< sc_lv<49> > tmp_17_fu_264_p4;
    sc_signal< sc_lv<52> > tmp_1_fu_274_p1;
    sc_signal< sc_lv<52> > tmp_5_fu_278_p1;
    sc_signal< sc_lv<52> > tmp_10_fu_281_p3;
    sc_signal< sc_lv<52> > neg_ti_fu_288_p2;
    sc_signal< sc_lv<5> > grp_fu_197_p2;
    sc_signal< sc_lv<6> > i_cast1_fu_306_p1;
    sc_signal< sc_lv<6> > tmp_7_fu_326_p2;
    sc_signal< sc_lv<5> > tmp_8_fu_344_p0;
    sc_signal< sc_lv<5> > tmp_8_fu_344_p1;
    sc_signal< sc_lv<10> > tmp_8_fu_344_p2;
    sc_signal< sc_lv<11> > tmp_15_fu_350_p3;
    sc_signal< sc_lv<15> > tmp_9_cast_fu_358_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st59_fsm_58;
    sc_signal< bool > ap_sig_311;
    sc_signal< sc_lv<32> > grp_fu_382_p3;
    sc_signal< sc_lv<32> > tmp_11_fu_372_p1;
    sc_signal< sc_lv<5> > grp_fu_382_p0;
    sc_signal< sc_lv<10> > extLd_cast_fu_368_p1;
    sc_signal< sc_lv<5> > grp_fu_382_p1;
    sc_signal< sc_lv<15> > grp_fu_382_p2;
    sc_signal< sc_logic > grp_fu_197_ap_start;
    sc_signal< sc_logic > grp_fu_197_ap_done;
    sc_signal< sc_lv<32> > tmp_13_fu_376_p3;
    sc_signal< sc_lv<32> > ap_return_preg;
    sc_signal< sc_lv<59> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<59> ap_ST_st1_fsm_0;
    static const sc_lv<59> ap_ST_st2_fsm_1;
    static const sc_lv<59> ap_ST_st3_fsm_2;
    static const sc_lv<59> ap_ST_st4_fsm_3;
    static const sc_lv<59> ap_ST_st5_fsm_4;
    static const sc_lv<59> ap_ST_st6_fsm_5;
    static const sc_lv<59> ap_ST_st7_fsm_6;
    static const sc_lv<59> ap_ST_st8_fsm_7;
    static const sc_lv<59> ap_ST_st9_fsm_8;
    static const sc_lv<59> ap_ST_st10_fsm_9;
    static const sc_lv<59> ap_ST_st11_fsm_10;
    static const sc_lv<59> ap_ST_st12_fsm_11;
    static const sc_lv<59> ap_ST_st13_fsm_12;
    static const sc_lv<59> ap_ST_st14_fsm_13;
    static const sc_lv<59> ap_ST_st15_fsm_14;
    static const sc_lv<59> ap_ST_st16_fsm_15;
    static const sc_lv<59> ap_ST_st17_fsm_16;
    static const sc_lv<59> ap_ST_st18_fsm_17;
    static const sc_lv<59> ap_ST_st19_fsm_18;
    static const sc_lv<59> ap_ST_st20_fsm_19;
    static const sc_lv<59> ap_ST_st21_fsm_20;
    static const sc_lv<59> ap_ST_st22_fsm_21;
    static const sc_lv<59> ap_ST_st23_fsm_22;
    static const sc_lv<59> ap_ST_st24_fsm_23;
    static const sc_lv<59> ap_ST_st25_fsm_24;
    static const sc_lv<59> ap_ST_st26_fsm_25;
    static const sc_lv<59> ap_ST_st27_fsm_26;
    static const sc_lv<59> ap_ST_st28_fsm_27;
    static const sc_lv<59> ap_ST_st29_fsm_28;
    static const sc_lv<59> ap_ST_st30_fsm_29;
    static const sc_lv<59> ap_ST_st31_fsm_30;
    static const sc_lv<59> ap_ST_st32_fsm_31;
    static const sc_lv<59> ap_ST_st33_fsm_32;
    static const sc_lv<59> ap_ST_st34_fsm_33;
    static const sc_lv<59> ap_ST_st35_fsm_34;
    static const sc_lv<59> ap_ST_st36_fsm_35;
    static const sc_lv<59> ap_ST_st37_fsm_36;
    static const sc_lv<59> ap_ST_st38_fsm_37;
    static const sc_lv<59> ap_ST_st39_fsm_38;
    static const sc_lv<59> ap_ST_st40_fsm_39;
    static const sc_lv<59> ap_ST_st41_fsm_40;
    static const sc_lv<59> ap_ST_st42_fsm_41;
    static const sc_lv<59> ap_ST_st43_fsm_42;
    static const sc_lv<59> ap_ST_st44_fsm_43;
    static const sc_lv<59> ap_ST_st45_fsm_44;
    static const sc_lv<59> ap_ST_st46_fsm_45;
    static const sc_lv<59> ap_ST_st47_fsm_46;
    static const sc_lv<59> ap_ST_st48_fsm_47;
    static const sc_lv<59> ap_ST_st49_fsm_48;
    static const sc_lv<59> ap_ST_st50_fsm_49;
    static const sc_lv<59> ap_ST_st51_fsm_50;
    static const sc_lv<59> ap_ST_st52_fsm_51;
    static const sc_lv<59> ap_ST_st53_fsm_52;
    static const sc_lv<59> ap_ST_st54_fsm_53;
    static const sc_lv<59> ap_ST_st55_fsm_54;
    static const sc_lv<59> ap_ST_st56_fsm_55;
    static const sc_lv<59> ap_ST_st57_fsm_56;
    static const sc_lv<59> ap_ST_st58_fsm_57;
    static const sc_lv<59> ap_ST_st59_fsm_58;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_38;
    static const sc_lv<32> ap_const_lv32_39;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<52> ap_const_lv52_A;
    static const sc_lv<105> ap_const_lv105_1999999999999A;
    static const sc_lv<32> ap_const_lv32_33;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<6> ap_const_lv6_3F;
    static const sc_lv<32> ap_const_lv32_68;
    static const sc_lv<105> ap_const_lv105_0;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_3A;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_sig_124();
    void thread_ap_sig_135();
    void thread_ap_sig_144();
    void thread_ap_sig_167();
    void thread_ap_sig_189();
    void thread_ap_sig_311();
    void thread_ap_sig_76();
    void thread_ap_sig_95();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st56_fsm_55();
    void thread_ap_sig_cseq_ST_st57_fsm_56();
    void thread_ap_sig_cseq_ST_st58_fsm_57();
    void thread_ap_sig_cseq_ST_st59_fsm_58();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_arr_address0();
    void thread_arr_address1();
    void thread_arr_ce0();
    void thread_arr_ce1();
    void thread_arr_d0();
    void thread_arr_we0();
    void thread_cou1_cast2_fu_225_p1();
    void thread_cou1_cast_fu_181_p1();
    void thread_cou1_fu_191_p2();
    void thread_exitcond_fu_315_p2();
    void thread_extLd_cast_fu_368_p1();
    void thread_grp_fu_197_ap_start();
    void thread_grp_fu_197_p0();
    void thread_grp_fu_197_p1();
    void thread_grp_fu_207_p0();
    void thread_grp_fu_207_p1();
    void thread_grp_fu_382_p0();
    void thread_grp_fu_382_p1();
    void thread_grp_fu_382_p2();
    void thread_i_1_fu_320_p2();
    void thread_i_cast1_fu_306_p1();
    void thread_i_cast_fu_310_p1();
    void thread_neg_mul_fu_259_p2();
    void thread_neg_ti_fu_288_p2();
    void thread_p_lshr_f_cast_fu_229_p4();
    void thread_p_shl1_cast_fu_167_p1();
    void thread_p_shl1_fu_159_p3();
    void thread_p_shl_cast_fu_155_p1();
    void thread_p_shl_fu_147_p3();
    void thread_tmp_10_fu_281_p3();
    void thread_tmp_11_fu_372_p1();
    void thread_tmp_13_fu_376_p3();
    void thread_tmp_14_fu_294_p3();
    void thread_tmp_15_fu_350_p3();
    void thread_tmp_17_fu_264_p4();
    void thread_tmp_1_cast_fu_239_p1();
    void thread_tmp_1_fu_274_p1();
    void thread_tmp_3_fu_221_p1();
    void thread_tmp_5_fu_278_p1();
    void thread_tmp_6_fu_243_p2();
    void thread_tmp_7_cast_fu_331_p1();
    void thread_tmp_7_fu_326_p2();
    void thread_tmp_8_fu_344_p0();
    void thread_tmp_8_fu_344_p1();
    void thread_tmp_8_fu_344_p2();
    void thread_tmp_9_cast_fu_358_p1();
    void thread_tmp_fu_185_p2();
    void thread_x_assign_cast_cast_cast_fu_177_p1();
    void thread_y_fu_171_p2();
    void thread_z_1_fu_362_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
